// screens
export const CHECKING = 'CHECKING';
export const INSTALL_DOCKER = 'INSTALL_DOCKER';
export const INSTALL_WSL2 = 'INSTALL_WSL2';
export const CONFIGURE_DOCKER = 'CONFIGURE_DOCKER';
export const CONFIGURE_GIGANTUM = 'CONFIGURE_GIGANTUM';
export const INSTALL_COMPLETE = 'INSTALL_COMPLETE';
export const ERROR = 'ERROR';

// actions
export const TRY_AGAIN_CONFIGURE_GIGANTUM = 'TRY_AGAIN_CONFIGURE_GIGANTUM';
export const TRY_AGAIN_INSTALL_DOCKER = 'TRY_AGAIN_INSTALL_DOCKER';
export const TRY_AGAIN_CONFIGURE_DOCKER = 'TRY_AGAIN_CONFIGURE_DOCKER';
export const SUCCESS = 'SUCCESS';
export const SKIP_CONFIGURE = 'SKIP_CONFIGURE';
